<a href="https://colab.research.google.com/github/salmaelhanchi/NeuroMatch_2026_Behaviour/blob/main/Data_Preperation_Notebook_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
from pathlib import Path

REPO_URL = "https://github.com/salmaelhanchi/NeuroMatch_2026_Behaviour.git"
REPO_DIR = Path("/content/NeuroMatch_2026_Behaviour")

if not REPO_DIR.exists():
    !git clone {REPO_URL} {REPO_DIR}

matches = list(REPO_DIR.rglob("data01_direction4priors.csv"))

if not matches:
    raise FileNotFoundError("data01_direction4priors.csv was not found inside the cloned repo.")

CSV_PATH = matches[0]
raw = pd.read_csv(CSV_PATH)

Loaded from: /content/NeuroMatch_2026_Behaviour/data01_direction4priors.csv
raw shape: 83,213 rows x 16 columns

,trial_index,trial_time,response_arrow_start_angle,motion_direction,motion_coherence,estimate_x,estimate_y,reaction_time,raw_response_time,prior_std,prior_mean,subject_id,experiment_name,experiment_id,session_id,run_id
0,1,0.000000,NaN,225,0.12,-1.749685,-1.785666,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
1,2,2.730730,NaN,225,0.12,-1.819693,-1.714269,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
2,3,4.913950,NaN,235,0.06,-1.562674,-1.951422,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
3,4,6.997296,NaN,225,0.06,-1.601388,-1.919781,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
4,5,9.097130,NaN,215,0.24,-1.639461,-1.887371,NaN,NaN,10,225,1,data01_direction4priors,11,1,1

In [7]:
print(f"Loaded from: {CSV_PATH}")
print(f"raw shape: {raw.shape[0]:,} rows x {raw.shape[1]} columns")
raw.head()

Loaded from: /content/NeuroMatch_2026_Behaviour/data01_direction4priors.csv
raw shape: 83,213 rows x 16 columns

,trial_index,trial_time,response_arrow_start_angle,motion_direction,motion_coherence,estimate_x,estimate_y,reaction_time,raw_response_time,prior_std,prior_mean,subject_id,experiment_name,experiment_id,session_id,run_id
0,1,0.000000,NaN,225,0.12,-1.749685,-1.785666,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
1,2,2.730730,NaN,225,0.12,-1.819693,-1.714269,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
2,3,4.913950,NaN,235,0.06,-1.562674,-1.951422,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
3,4,6.997296,NaN,225,0.06,-1.601388,-1.919781,NaN,NaN,10,225,1,data01_direction4priors,11,1,1
4,5,9.097130,NaN,215,0.24,-1.639461,-1.887371,NaN,NaN,10,225,1,data01_direction4priors,11,1,1